behaviors:
  AgentController:
    trainer_type: ppo
    time_horizon: 32 
    max_steps: 1e6 
    hyperparameters:
      learning_rate: 3e-4 
      batch_size: 1024 
      buffer_size: 4500
      num_epoch: 10 
    network_settings:
      normalize: true
      num_layers: 3 
      hidden_units: 256 
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    summary_freq: 50000
    threaded: true
torch_settings:
  device: cpu
